### DISCUSSION TITLE
Proposal: `decimal` (fixed point) primitive type

### DISCUSSION THREAD

**Discussion by tliron** [oasis-tcs/tosca-specs#229] [Ideas]
For TOSCA 2.1.

Decimals are fractional representations that are not stored as IEEE floating points. A.k.a. "fixed point".

They are necessary for specific applications that cannot tolerate the imprecise precision of floating points, most notably currency. They imply not only fixed point storage, but also fixed point arithmetic operations.

Due to the limitations of YAML parsing I propose that they be represented as strings. Examples:

```yaml
data_types:
  BankAccount:
    properties:
      balance: decimal

service_template:
  node_templates:
    my-account:
      properties:
        balance: '-127.40' # trailing zeroes are optional

    your-account:
      properties:
        balance: { $product: [ $get_property: [ my-account, balance ], '.02' ] } # note we seem to be multiplying by a string
```
