### ISSUE TITLE
implicit null value in definitions

### ISSUE THREAD

**Issue by philippemerle** [oasis-tcs/tosca-specs#265]
**Issue Description**

The following service template contains 6 implicit null values in definitions:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
data_types: # null value implicitly
capability_types:
  CT: # null value implicitly
node_types:
  NT:
    description: # null value implicitly
    capabilities: # null value implicitly
    requirements: # null value implicitly
topology_template:
  node_templates:
    n1:
      type: tosca.nodes.Compute
      capabilities:
        os: # null value implicitly
```

TOSCA specification seems to **not explicity** specify if and when null values in definitions are allowed.

For this service template
* Ubicity Validator reports only one error on `data_types:`.
* Puccini reports 6 errors.
* Cloudnet TOSCA toolbox reports 6 errors.

This repository contains some service templates with null values in definitions: 
* https://github.com/oasis-open/tosca-community-contributions/blob/master/examples/1.3/examples-from-spec/inputs-and-outputs/inputs-and-outputs.yaml#L34
* https://github.com/oasis-open/tosca-community-contributions/blob/master/examples/basic-template/basic-template.yml#L18

**Proposed Resolution**

Explicitly specify in TOSCA 2.0 if and when null values in definitions are allowed.
