### ISSUE TITLE
Use condition syntax in node filters and capability filters

### ISSUE THREAD

**Issue by lauwers** [oasis-tcs/tosca-specs#272]
I have a need to define more complex requirement fulfillment logic than what can be expressed using node and capability filters. I believe the existing condition syntax could be used for this purpose. The following example shows how condition syntax could express **_anti-collocation_** behavior:

```
tosca_definitions_version: tosca_2_0

capability_types:
  Host:
    description: for hosting software components

relationship_types:
  HostedOn:
    description: relationship to hosting container

node_types:

  Host:
    properties:
      uuid:
        type: string
    capabilities:
      host:
        type: Host

  SoftwareComponent:
    requirements:
      - host:
          capability: Host
          relationship: HostedOn

service_template:

  node_templates:

    host1:
      type: Host
      properties:
        uuid: host.1
      
    host2:
      type: Host
      properties:
        uuid: host.2
      
    host3:
      type: Host
      properties:
        uuid: host.3
      
    software1:
      type: SoftwareComponent
      requirements:
        - host:
            node: Host

    software2:
      type: SoftwareComponent
      requirements:
        - host:
            node: Host
            filter:
              - not:
                  [TARGET, uuid] : { equal: [software1, RELATIONSHIP, host, TARGET, uuid ] }
```
