### ISSUE TITLE
Function definitions are  under-specified

### ISSUE THREAD

**Issue by lauwers** [oasis-tcs/tosca-specs#297]
The [function definition](https://github.com/oasis-tcs/tosca-specs/blob/published/tosca_2_0/TOSCA-v2.0-csd07.md#function-definitions) syntax includes an `implementation` keyword that expects a simple string value. The specification is unclear about how this string value is expected to be used and how function arguments are expected to this implementation.

**Comment by pmjordan** [comment]
Agreed. In fact if one follows the text rather than the examples the simple string should be the symbolic name of an artifact. Implementation in functions is said to be as per Operation and Notification Implementations but that section says artifacts are defined in node type or node template and that is not appropriate for custom functions.

**Comment by tliron** [comment]
We generally have not done a good job with showing which definitions have short forms (usually single strings). You have to find that documentation in the examples that are below the actual keyname table. Something to fix in future versions. I think all syntax options should be clearly shown at the top.

Anyway, there is this note in section 11.8:

> The following single-line grammar may be used when only a primary implementation artifact name is needed:
>
> `implementation: <primary_artifact_name>`
>
> This notation can be used when the primary artifact name uniquely identifies the artifact because it refers to an artifact specified in the artifacts section of a type or template.

So, instead of the whole artifact definition we are allowed to just give the name of the artifact. But, as Paul points out, there are no artifacts associated with function definitions. This, to me, implies that a single-string shortcut cannot be used in function definitions. Thus the shortest syntax you can get away with would be something like this:

```
functions:
  get_kubernetes:
    signatures:
    - arguments:
      - type: string
      result:
        type: string
      implementation:
        primary:
          type: Plugin
          file: debug/kubernetes_functions.wasm
```
