### ISSUE TITLE
"single-line relationship grammar" is multi line

### ISSUE THREAD

**Issue by koppor** [oasis-tcs/tosca-specs#75]
It is promised that there is a single-line grammar for a "symbolic name of a relationship template to use". However, the grammar is the same as above

![image](https://github.com/user-attachments/assets/dfe37d95-45df-4060-b0a5-5b7cca1bad46)

https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd06/TOSCA-v2.0-csd06.html#872-requirement-assignment-grammar

**Comment by lauwers** [comment]
The examples are correct, but the text describing the examples is confusing. The example you're referencing uses a `<relationship_template_name>`. The example right above it uses a `<relationship_type_name>`. We'll try to make the descriptions less confusing.

**Comment by lauwers** [comment]
Clarifications have been merged into the OASIS repository

**Comment by koppor** [comment]
I would have assumed that I can just list a single relationship template (instead of listing capabilities and other things). Thus, it would really be a single line grammar.

**Comment by lauwers** [comment]
Could you provide an example of the *single line grammar* you have in mind?

**Comment by koppor** [comment]
I think, it is as simple as

```xml
<requirement_name>:
  relationship: <relationship_template_name>
```

(I haven't fully thought through - however, this snippet would match the paragraph "As stated in the description of the supported keynames [...]")

**Comment by koppor** [comment]
Side story: Maybe, I am struggling with the term **single-line grammar**

Other places in the spec show a single line. - Meaning count(lines) == 1.

![image](https://github.com/user-attachments/assets/eaea4710-eec1-4a30-b814-ff4c16d0bbef)

![image](https://github.com/user-attachments/assets/88e20b88-93b6-4062-abf9-0e1f619a8a13)

![image](https://github.com/user-attachments/assets/38119765-c13c-4046-921b-d497dd60b1d5)

(and more)

---

Here it is "OK", the reader should understand that 1 and 2 are to be read as "single-line"

![image](https://github.com/user-attachments/assets/3dfa09b3-6df3-4d12-9a19-474e1bf52e73)

**Comment by koppor** [comment]
Minimal example:

I want to model:

a --> httpConnectsTo --> b

httpConnectsTo Port 8080

In TOSCA 1.0, I would introduce a relationship type `HttpConnectsTo` with property `port`. Then a relationship template `conn` with property `port` filled with `8080`. Then connect node template using `conn` with `b`. - Maybe, this is old-fashioned?

---

I am checking https://github.com/frankakn/cloud-native-deployment/blob/main/DeploymentOptions/TeaStore-managed-k8s-self-managed-nodes.yaml to get a kind of more complete example.

Node Types:

```yaml
    cna-modeling.entities.Infrastructure:
      ...
```

Node Templates:

```yaml
    aws_eks_cluster:
      type: cna-modeling.entities.Infrastructure
      requirements:
        - host:
            node: ec2_node
            relationship: ec2_node_hosts_aws_eks_cluster
    ec2_node:
      type: cna-modeling.entities.Infrastructure
```

Relationship Templates:

```yaml
    ec2_node_hosts_aws_eks_cluster:
      type: cna-modeling.entities.HostedOn.DeploymentMapping
      properties:
        deployment: automated-declarative
```

---

Summary: It seems not to be a single-line grammar (for the whole thing), but a three-line grammar.
